	AREA MULTIPLY , CODE, READONLY
ENTRY ;Mark first instruction to execute
START
	MOV r1,#15 ; STORE FIRST NUMBER IN R1
	MOV r2,#3200 ; STORE SECOND NUMBER IN R2
	MUL r3,r1,r2 ; MULTIPLICATION
	NOP
	NOP
	NOP
BACK B BACK
	END ;Mark end of file