	AREA SUM,CODE,READONLY
ENTRY
	MOV R1,#10    ; LOADING VALUE 10 IN REGISTER R1
	MOV R2,#0     ; LOADING VALUE  0 IN REGISTER R2
LOOP
	ADD R2,R2,R1  ; ADDING VALUE LOADED IN R1 TO R2 AND STORING IN R2
	SUBS R1,#0x01 ;DECREMENTING R1 BY 1
	BNE LOOP      ;REPEAT TILL R1 GOES TO 0
BACK B BACK
	END